//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchDayApp.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchDayApp.Domain.Resources.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado usuário com o email especificado.
        /// </summary>
        public static string ME001 {
            get {
                return ResourceManager.GetString("ME001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um erro inesperado aconteceu ao resetar a senha.
        /// </summary>
        public static string ME002 {
            get {
                return ResourceManager.GetString("ME002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar alterações no banco de dados.
        /// </summary>
        public static string ME003 {
            get {
                return ResourceManager.GetString("ME003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login com a combinação Email/senha é invalida.
        /// </summary>
        public static string ME004 {
            get {
                return ResourceManager.GetString("ME004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha no registro de usuário.
        /// </summary>
        public static string ME005 {
            get {
                return ResourceManager.GetString("ME005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login efetuado com sucesso.
        /// </summary>
        public static string MS001 {
            get {
                return ResourceManager.GetString("MS001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha redefinida com sucesso.
        /// </summary>
        public static string MS002 {
            get {
                return ResourceManager.GetString("MS002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrado com sucesso.
        /// </summary>
        public static string MS003 {
            get {
                return ResourceManager.GetString("MS003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email inválido.
        /// </summary>
        public static string MV001 {
            get {
                return ResourceManager.GetString("MV001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida.
        /// </summary>
        public static string MV002 {
            get {
                return ResourceManager.GetString("MV002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de email já existente.
        /// </summary>
        public static string MV003 {
            get {
                return ResourceManager.GetString("MV003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username já existente.
        /// </summary>
        public static string MV004 {
            get {
                return ResourceManager.GetString("MV004", resourceCulture);
            }
        }
    }
}
