//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchDayApp.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dicionario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dicionario() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchDayApp.Domain.Recursos.Dicionario", typeof(Dicionario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi encontrado usuário com o email especificado.
        /// </summary>
        public static string ME001 {
            get {
                return ResourceManager.GetString("ME001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Um erro inesperado aconteceu ao resetar a senha.
        /// </summary>
        public static string ME002 {
            get {
                return ResourceManager.GetString("ME002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao salvar alterações no banco de dados.
        /// </summary>
        public static string ME003 {
            get {
                return ResourceManager.GetString("ME003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login com a combinação Email/senha é invalida.
        /// </summary>
        public static string ME004 {
            get {
                return ResourceManager.GetString("ME004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha no registro de usuário.
        /// </summary>
        public static string ME005 {
            get {
                return ResourceManager.GetString("ME005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Requisição inválida.
        /// </summary>
        public static string ME006 {
            get {
                return ResourceManager.GetString("ME006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login efetuado com sucesso.
        /// </summary>
        public static string MS001 {
            get {
                return ResourceManager.GetString("MS001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha redefinida com sucesso.
        /// </summary>
        public static string MS002 {
            get {
                return ResourceManager.GetString("MS002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registrado com sucesso.
        /// </summary>
        public static string MS003 {
            get {
                return ResourceManager.GetString("MS003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Email inválido.
        /// </summary>
        public static string MV001 {
            get {
                return ResourceManager.GetString("MV001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha inválida.
        /// </summary>
        public static string MV002 {
            get {
                return ResourceManager.GetString("MV002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço de email já existente.
        /// </summary>
        public static string MV003 {
            get {
                return ResourceManager.GetString("MV003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Username já existente.
        /// </summary>
        public static string MV004 {
            get {
                return ResourceManager.GetString("MV004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Primeiro nome não pode ser nulo ou vazio.
        /// </summary>
        public static string MV005 {
            get {
                return ResourceManager.GetString("MV005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Primeiro nome deve conter mais de 4 caracteres.
        /// </summary>
        public static string MV006 {
            get {
                return ResourceManager.GetString("MV006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ultimo nome não pode ser nulo ou vazio.
        /// </summary>
        public static string MV007 {
            get {
                return ResourceManager.GetString("MV007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ultimo nome deve conter mais de 4 caracteres.
        /// </summary>
        public static string MV008 {
            get {
                return ResourceManager.GetString("MV008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Primeiro nome não é válido.
        /// </summary>
        public static string MV009 {
            get {
                return ResourceManager.GetString("MV009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ultimo nome não é válido.
        /// </summary>
        public static string MV010 {
            get {
                return ResourceManager.GetString("MV010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço de email inválido.
        /// </summary>
        public static string MV011 {
            get {
                return ResourceManager.GetString("MV011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Username não pode ser nulo ou vazio.
        /// </summary>
        public static string MV012 {
            get {
                return ResourceManager.GetString("MV012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha não pode ser nula ou vazia.
        /// </summary>
        public static string MV013 {
            get {
                return ResourceManager.GetString("MV013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha não corresponde a um padrão forte.
        /// </summary>
        public static string MV014 {
            get {
                return ResourceManager.GetString("MV014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirmação da senha não é igual a senha criada.
        /// </summary>
        public static string MV015 {
            get {
                return ResourceManager.GetString("MV015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do time não pode ser nulo ou vazio.
        /// </summary>
        public static string MV016 {
            get {
                return ResourceManager.GetString("MV016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do time deve conter mais de 4 caracteres.
        /// </summary>
        public static string MV017 {
            get {
                return ResourceManager.GetString("MV017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do time inválido.
        /// </summary>
        public static string MV018 {
            get {
                return ResourceManager.GetString("MV018", resourceCulture);
            }
        }
    }
}
