name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore
      run: dotnet restore .//server//
    - name: Build
      run: dotnet build .//server// --configuration Release --no-restore
    - name: Unit Test
      run: dotnet test .//server//tests//MatchDayApp.UnitTest// --no-restore --verbosity minimal
#     - name: Integration Test
#       run: dotnet test .//server//tests//MatchDayApp.IntegrationTest// --no-restore --verbosity minimal
    - name: Publish
      run: dotnet publish .//server//src//MatchDayApp.Api// --configuration Release --framework netcoreapp3.1 --no-restore -v minimal -o output/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: artifact
        path: /home/runner/work/matchday-app/matchday-app/output/
