name: Front-end workflow
 
on:
  push:
    branches: [ master ]
    paths-ignore: 
     - server/**
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - uses: actions/setup-node@master
      - name: Install Packages and Build Application
        run: |
         cd web
         npm install
         npm run build
      
      - uses: actions/upload-artifact@v2.2.1
        with:
          name: matchdayapp-web-artifacts
          path: /home/runner/work/matchday-app/matchday-app/web/dist/
