name: Front-end workflow
 
on:
  push:
    branches: [ master ]
    paths-ignore: 
     - server/**
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Change into webapp folder
        run: cd web/
      
      - uses: actions/setup-node@master
      - name: Install Packages and Build Application
        run: |
         npm install
         npm run build
      
      - uses: actions/upload-artifact@v2.2.1
        with:
          name: matchdayapp-web-artifacts
          path: /home/runner/work/dist/
